appName: Crop Health
APP:
  Name: Crop Health
  Logo: app_logo.png
  Location: Sudan
Client:
  Name: FGM International
  Logo: fgm.png
  Location: Sudan
  DataPath: ./clients/FGM.geojson
  # DataPath: ./clients/Fcugir-007498-geojson.json
Sentinel:
  InstanceId: b87f70ab-7325-4739-ad66-218f8728a5b6
  ClientId: 90b8c212-e4cf-41c9-934b-66bca4bb6002
  ClientSecret: c1Cfvk6JadsFjSu0seTF3lvtP9UD9IGl

StartDate: 2020-06-01
appSemanticVersion: 0.9.3
ClientName: FGM
